### ISSUE TITLE
Error in str_replace_all(bedFile, "19", "38") : object 'bedFile' not found

### ISSUE THREAD

**Issue by shawez** [likelet/CaMutQC#35]
Hello, 
I can successfully load my VEP annotated VCF file using _vcfToMAF_ function. 

my_MAF <- vcfToMAF("vepAnnoted_Strelka.vcf", inputStrelka = 'SNV')

_vepAnnoted_Strelka.vcf loaded successfully!
VCF to MAF conversion is in process...
VCF to MAF conversion has been done successfully!_

Then, I am trying to run calTMB function on with OR without passing BED file. 

TMB_value <- calTMB(my_MAF,  bedFile = readBed("/Homo_sapiens.GRCh38.91.v2.bed"), assay = 'MSK-v1' )

But in both the case, I am getting the following error.

**Error in str_replace_all(bedFile, "19", "38") : 
  object 'bedFile' not found
In addition: Warning message:
In readBedPanel(assay, genVer, maf) :
  Bed files in CaMutQC are not accurate. The result serves only as a reference.**

My file was mapped using GRCh38 genome and Strelka was used for variant calling. 

Any help would be appreciated.

Thanks in advance.

Best,
Shawez

**Comment by shawez** [comment]
Hello,
Thank you very much for your reply.
Now, I have tried the following code:

_MB_value <- calTMB(my_MAF, bedFile = "/Homo_sapiens.GRCh38.91.v2.bed", assay = 'MSK-v1' )_

But still same error is there

**Error in str_replace_all(bedFile, "19", "38") : 
  object 'bedFile' not found
In addition: Warning message:
In readBedPanel(assay, genVer, maf) :
  Bed files in CaMutQC are not accurate. The result serves only as a reference.**

I checked the path and this bed file exists. 
Any suggestions on it.

Thank you.
Best,
Shawez

**Comment by Wangxin555** [comment]
Hi, 
No problem showed when I tested on my PC, but some code of `calTMB` did change recently.
Please try to update this package using `devtools::install_github("likelet/CaMutQC")`

**Comment by Wangxin555** [comment]
Hi,

Could you try to install the latest version of CaMutQC, which should be 0.99.1?
Simply run `devtools::install_github("likelet/CaMutQC")` will work.

**Comment by shawez** [comment]
It solved the issue!

Thanks a lot,
